name: CI
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.github/*_TEMPLATE/**'
      - '.github/workflows/localisation.yml'
      - '.gitignore'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.github/*_TEMPLATE/**'
      - '.github/workflows/localisation.yml'
      - '.gitignore'
      - '.vscode/**'
  workflow_dispatch:
    inputs:
      sign:
        description: Sign binaries
        type: choice
        options:
          - 'no'
          - test-signing
          - release-signing
        default: test-signing

defaults:
  run:
    shell: bash
env:
  OPENRCT2_BUILD_SERVER: GitHub
  OPENRCT2_ORG_TOKEN: ${{ secrets.OPENRCT2_ORG_TOKEN }}
  BACKTRACE_IO_TOKEN: ${{ secrets.BACKTRACE_IO_TOKEN }}
  OPENRCT2_VERSION: 0.5.4

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_variables:
    name: Get version info
    runs-on: ubuntu-24.04 # This job is too heavy for ubuntu-slim. It takes almost a minute to checkout the code on slim vs 23s on ubuntu-24.04.
    # We want to sign tagged releases with release certificates, but it is only allowed to be ran manually.
    # Disable automatic runs for tags and force release signing for tags.
    if: |
      (startsWith(github.ref, 'refs/tags/v') && github.event_name == 'workflow_dispatch' && github.event.inputs.sign == 'release-signing') ||
      (!startsWith(github.ref, 'refs/tags/v') && github.event.inputs.sign != 'release-signing')
    outputs:
      name: ${{ steps.artifact-name.outputs.name }}
      describe: ${{ steps.ghd.outputs.describe }}
      short-sha: ${{ steps.ghd.outputs.short-sha }}
      distance: ${{ steps.ghd.outputs.distance }}
      tag: ${{ steps.ghd.outputs.tag }}
      push: ${{ steps.setenv.outputs.push }}
      sign: ${{ steps.sign.outputs.sign }}
      certificate: ${{ steps.sign.outputs.certificate }}
    steps:
      # We need to fetch entire repo to get the tags and correctly run `describe`
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      # We cannot use proudust/gh-describe, as it reports incorrect (too short) short-sha
      - name: Git describe
        id: ghd
        run: |
          TAG=$(git describe --tags --abbrev=0)
          DESCRIBE=$(git describe --tags)
          SHORT_SHA=$(git rev-parse --short HEAD)
          DISTANCE=$(git rev-list --count $TAG..HEAD)
          echo "tag=$TAG"
          echo "describe=$DESCRIBE"
          echo "short-sha=$SHORT_SHA"
          echo "distance=$DISTANCE"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "describe=$DESCRIBE" >> $GITHUB_OUTPUT
          echo "short-sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "distance=$DISTANCE" >> $GITHUB_OUTPUT
      - name: Set env
        id: setenv
        run: |
          . scripts/setenv
          echo "push=$OPENRCT2_PUSH"
          echo "push=$OPENRCT2_PUSH" >> $GITHUB_OUTPUT
      # Name now uses the same format as "describe"
      - name: Get artifact name
        id: artifact-name
        run: |
          echo "name=${{ steps.ghd.outputs.describe }}"
          echo "name=${{ steps.ghd.outputs.describe }}" >> $GITHUB_OUTPUT
      - name: Sign
        id: sign
        env:
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
        run: |
          sign=${{ env.SIGNPATH_API_TOKEN != '' && github.event.inputs.sign != 'no' && (needs.build_variables.outputs.push || startsWith(github.ref, 'refs/tags/v')) }}
          # if using workflow_dispatch, use the provided certificate
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            certificate=${{ github.event.inputs.sign }}
          else
            # Default to no signing
            certificate=no
            sign=false
          fi
          echo "sign=$sign"
          echo "certificate=$certificate"
          echo "sign=$sign" >> $GITHUB_OUTPUT
          echo "certificate=$certificate" >> $GITHUB_OUTPUT
  # lint-commit:
  #   name: Lint Commit Message
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-24.04
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
  #       with:
  #         fetch-depth: 0
  #     - name: Lint Commit Messages
  #       uses: wagoid/commitlint-github-action@v5
  #       with:
  #         configFile: .commitlint.json
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-24.04
    container: ghcr.io/openrct2/openrct2-build:26-format
    permissions:
      pull-requests: write
      contents: read
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - run: git config --global --add safe.directory $PWD
      - name: Run clang-format
        id: clang_format
        run: scripts/check-code-formatting
      - uses: parkerbxyz/suggest-changes@v3
        if: github.event_name == 'pull_request' && failure()
        with:
          comment: 'Please commit the suggested changes from clang-format.'
          event: 'REQUEST_CHANGES'
  check-changelog-formatting:
    name: Check changelog formatting
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run check-changelog-formatting
        run: scripts/check-changelog-formatting
  g2dat:
    name: Graphics .dat files
    runs-on: ubuntu-slim
    needs: build_variables
    steps:
      - name: Checkout OpenRCT2
        uses: actions/checkout@v7
        with:
          path: OpenRCT2
      - name: Download gxc
        run: |
          curl -Lo tools.tar.gz https://github.com/OpenRCT2/libsawyer/releases/download/v1.4.0/libsawyer-tools-linux-x64.tar.gz
          mkdir -p "$GITHUB_WORKSPACE/bin"
          tar -C "$GITHUB_WORKSPACE/bin" -xf tools.tar.gz
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Build graphics .dat files
        run: |
          OpenRCT2/scripts/build-graphics-dat "$PWD"
      - name: Upload graphics .dat files
        uses: actions/upload-artifact@v6
        with:
          name: graphics-${{ needs.build_variables.outputs.name }}
          path: |
            g2.dat
            palettes.dat
            fonts.dat
            tracks.dat
  android-libs:
    name: Android (${{ matrix.arch }})
    runs-on: ubuntu-24.04
    needs: [check-code-formatting, build_variables]
    container: ghcr.io/openrct2/openrct2-build:26-android
    strategy:
      fail-fast: false
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.21
        with:
          key: android-${{ matrix.arch }}
      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          # The gradle cache is by default ~/.gradle/caches, but ~ gets resolved by GitHub Actions to the runner's
          # home directory (/home/github), not the user inside the container (/root). Name the path explicitly.
          path: /root/.gradle/caches
          # The cache key needs to occasionally be updated as the cache itself is immutable, otherwise it can grow stale. The easiest way to force this is to include the tag, which changes every month.
          # Keep in sync with the cache key used in the `android` job.
          key: gradle-${{ runner.os }}-${{ needs.build_variables.outputs.tag }}-android-${{ hashFiles('src/openrct2-android/build.gradle', 'src/openrct2-android/settings.gradle', 'src/openrct2-android/app/build.gradle', 'src/openrct2-android/gradle.properties', 'src/openrct2-android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ needs.build_variables.outputs.tag }}-android-
      - name: Install GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master
      - name: Build Native Libs
        run: |
          . scripts/setenv
          pushd src/openrct2-android
          ./gradlew app:externalNativeBuildRelease -PabiFilter=${{ matrix.arch }} -PskipAssets -PskipJava
          popd
      - name: Upload Native Libs
        uses: actions/upload-artifact@v6
        with:
          name: android-libs-${{ matrix.arch }}
          path: src/openrct2-android/app/build/intermediates/cmake/release/obj/${{ matrix.arch }}
          if-no-files-found: error

  android:
    name: Android
    runs-on: ubuntu-24.04
    needs: [android-libs, build_variables, g2dat]
    container: ghcr.io/openrct2/openrct2-build:26-android
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          # The gradle cache is by default ~/.gradle/caches, but ~ gets resolved by GitHub Actions to the runner's
          # home directory (/home/github), not the user inside the container (/root). Name the path explicitly.
          path: /root/.gradle/caches
          # Keep in sync with the cache key used in the `android-libs` job.
          key: gradle-${{ runner.os }}-${{ needs.build_variables.outputs.tag }}-android-${{ hashFiles('src/openrct2-android/build.gradle', 'src/openrct2-android/settings.gradle', 'src/openrct2-android/app/build.gradle', 'src/openrct2-android/gradle.properties', 'src/openrct2-android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ needs.build_variables.outputs.tag }}-android-
      - name: Setup keystore
        run: |
          echo "${{ secrets.OPENRCT2_KEYSTORE_CONTENTS }}" | base64 -d > keystore.jks
          echo "OPENRCT2_KEYSTORE_FILE=${{ github.workspace }}/keystore.jks" >> $GITHUB_ENV
          echo "OPENRCT2_KEYSTORE_PASSWORD=${{ secrets.OPENRCT2_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
      - name: Download all libs
        uses: actions/download-artifact@v7
        with:
          pattern: android-libs-*
          path: artifacts/android-libs
      - name: Move libs to project
        run: |
          mkdir -p src/openrct2-android/app/libs
          for arch in armeabi-v7a arm64-v8a x86_64; do
            if [ -d "artifacts/android-libs/android-libs-$arch" ]; then
              mkdir -p src/openrct2-android/app/libs/$arch
              mv artifacts/android-libs/android-libs-$arch/* src/openrct2-android/app/libs/$arch/
            else
              echo "::warning title=Missing libraries::Warning: No libs found for $arch"
            fi
          done
      - name: Download graphics .dat files
        uses: actions/download-artifact@v7
        with:
          name: graphics-${{ needs.build_variables.outputs.name }}
          path: bin/data
      - name: Build OpenRCT2
        run: |
          . scripts/setenv
          export OPENRCT2_DAT_DIR="$GITHUB_WORKSPACE/bin/data"
          pushd src/openrct2-android
          ./gradlew app:assembleRelease -PskipNativeBuild
          popd
          mkdir -p artifacts
          mv src/openrct2-android/app/build/outputs/apk/release/app-release.apk artifacts/OpenRCT2-${{ needs.build_variables.outputs.name }}-android.apk
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v6
        with:
          name: OpenRCT2-${{ needs.build_variables.outputs.name }}-Android
          path: artifacts
          if-no-files-found: error
      - name: Upload gradle issues
        uses: actions/upload-artifact@v6
        with:
          name: OpenRCT2-${{ needs.build_variables.outputs.name }}-gradle-issues
          path: src/openrct2-android/build/reports/problems/problems-report.html
          if-no-files-found: ignore
